import { h_actualroomrate } from "./h_actualroomrate.model";

export class HRoomallotment {
    VoucherNo: string;
    VoucherCode: number;
    RefVoucherNo: string;
    RefVoucherCode: number;
    RoomId: number;
    RoomCode: string;
    RoomRent: number;
    CustomerID: number;
    CustomerName: string;
    CustomerFirstName: string;
    CustomerSecondName: string;
    CustomerDOB: Date;
    PassportNo: string;
    AddressLine1: string;
    AddressLine2: string;
    City: string;
    CountryId: number;
    emailId: string;
    PhoneNo: string;
    BillTo: number;
    BookEntryType: number;
    BookedBy: number;
    ReservationMode: string;

    IsBreakFastIncluded: number;
    CouponVoucherNo: string;
    CouponVoucherCode: number;
    Phone2: number;
    EmergencyNo: string;
    ExpiryDate: Date;
    BookingDate: Date;
    BookingTime: Date;
    CheckoutEstimatedDate: Date;
    CheckoutEstimatedDays: Date;
    CheckinTime: Date;
    CheckinDate: Date;
    CheckoutDate: Date;
    CheckoutTime: Date;
    StayedDays: number;
    NoOFExtraBed: number;
    NoOFChilds: number;
    PricePreBed: number;
    ChildPricePerBed: number;
    Remarks: string;
    TotalDiscount: number;
    TotalDiscPer: number;
    NoOfGuest: number;
    ClassID: number = 0;
    IsDinnerInclude: number = 0;
    IsLunchInclude: number = 0;
    IsAllInclude: number = 0;
    BreakFastRate: number = 0;
    LunchRate: number = 0;
    DinnerRate: number = 0;
    AllIncludeRate: number = 0;
    TaxRateID: number = 0;
    TaxPercent: number = 0;
    TaxAmount: number = 0;
    TotalAmount: number = 0;
    roomrates:h_actualroomrate[]=[];
}
