export class h_roombooking {
    VoucherNo: string = "";
    VoucherCode: number = 0;
    RefVoucherNo: string = "";
    RefVoucherCode: number = 0;
    ClientID: number = 0;
    RoomCode: string = "";
    RoomRent: number = 0;
    CustomerID: number = 0;
    CustomerName: string = "";
    CustomerFirstName: string = "";
    CustomerSecondName: string = "";
    CustomerDOB: Date;
    PassportNo: string = "";
    AddressLine1: string = "";
    AddressLine2: string = "";
    City: string = "";
    Country: string = "";
    emailId: string = "";
    PhoneNo: string = "";
    BillTo: number = 0;
    BookEntryType: string = "";
    BookedBy: string = "";
    ReservationMode: string = "";
    IsBreakFastIncluded: number = 0;
    CouponVoucherNo: string = "";
    CouponVoucherCode: number = 0;
    CredicardNo: string = "";
    CreditCardType: string = "";
    ExpiryDate: Date;
    BookingDate: Date;
    BookingTime: Date;
    CheckoutEstimatedDate: Date;
    CheckoutEstimatedDays: number = 0;
    CheckinTime: Date;
    CheckinDate: Date;
    CheckoutDate: Date;
    CheckoutTime: Date;
    StayedDays: number = 0;
    NoOFExtraBed: number = 0;
    NoOFChilds: number = 0;
    PricePreBed: number = 0;
    ChildPricePerBed: number = 0;
    Remarks: string = "";
    TotalDiscount: number = 0;
    TotalDiscPer: number = 0;
    NoOfGuest: number = 0;
    ClassID: number = 0;
    IsDinnerInclude: number = 0;
    IsLunchInclude: number = 0;
    IsAllInclude: number = 0;
    BreakFastRate: number = 0;
    LunchRate: number = 0;
    DinnerRate: number = 0;
    AllIncludeRate: number = 0;
    TaxRateID: number = 0;
    TaxPercent: number = 0;
    TaxAmount: number = 0;
    TotalAmount: number = 0;
    
}