import { RouterUrlsType } from "../models/router-urls-type";

export const RouterUrls: RouterUrlsType = {
  MyAccount: "myaccount",
  Login: "login",
  Register: "register",
  YourAccount: "youraccount",
  YourAddress: "youraddress",
  Address: "address",
  LoginSecurity: "loginsecurity",
  Shop: "shop",
  OrderHistory: "orderhistory",
  WishList: "wishlist",
  Checkout: "checkout",
  ViewCart: "viewcart",
  ProductDescription: "productdescription",
  Products: "products",
  Dashboard: "dashboard",
  SuperDeals: "superdeals",
  TrendingStyles: "manufacturers",
  BomTools: "bomtools",
  AddAddress: "address",
  EditAddress: "editaddress",
  ForgotPassword: "forgotpassword",
  PaymentOptions: "paymentoptions",
  SearchListing: "searchlisting",
  Components: "manufacturers",
  BusinessSetting: "businesssetting",
  AddAdmin: "addadmin",
  AboutUs: "aboutus",
  ContactUs: "contactus",
  TermsConditions: "termsconditions",
  DeliveryReturns: "deliveryreturns",
  PrivacyPolicy: "privacypolicy",
  YourOrders: "yourorders",
  Billingaddress:"Billingaddress",
  EditBillingaddress:"editBillingaddress",
  DefaultBillingAddress:"defaultbillingaddress",
  DefaultShippingAddress:"defaultshippingaddress"
};
